// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Account
{
    public short Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual DinerProfile? DinerProfile { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual RestaurantProfile? RestaurantProfile { get; set; }

    public virtual Role Role { get; set; }
}