// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public short DinerId { get; set; }

    public short RestaurantId { get; set; }

    public short? TableId { get; set; }

    public DateTime BookingTime { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual DinerProfile Diner { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual RestaurantProfile Restaurant { get; set; }

    public virtual RestaurantTable Table { get; set; }

    public virtual Transaction Transaction { get; set; }
}