// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class DinerProfile
{
    public short AccountId { get; set; }

    public string AvatarUrl { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public int? Age { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Job { get; set; }

    public string Description { get; set; }

    public string FacebookUrl { get; set; }

    public string TiktokUrl { get; set; }

    public int? RewardPoints { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Favourite> Favourites { get; set; } = new List<Favourite>();

    public virtual ICollection<FoodReview> FoodReviews { get; set; } = new List<FoodReview>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}