// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Favourite
{
    public short Id { get; set; }

    public short DinerId { get; set; }

    public short RestaurantId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual DinerProfile Diner { get; set; }

    public virtual RestaurantProfile Restaurant { get; set; }
}