// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class FoodReview
{
    public short ReviewId { get; set; }

    public short FoodId { get; set; }

    public short DinerId { get; set; }

    public DateTime Date { get; set; }

    public int? Rating { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsAnonymous { get; set; }

    public virtual DinerProfile Diner { get; set; }

    public virtual RestaurantMenu Food { get; set; }
}