// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class OrderDetail
{
    public short OrderDetailId { get; set; }

    public short FoodId { get; set; }

    public short OrderId { get; set; }

    public int NumberOfFood { get; set; }

    public decimal? FoodPrice { get; set; }

    public virtual RestaurantMenu Food { get; set; }

    public virtual Order Order { get; set; }
}