// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Order
{
    public short OrderId { get; set; }

    public short DinerId { get; set; }

    public short RestaurantId { get; set; }

    public short? PromotionId { get; set; }

    public DateTime Date { get; set; }

    public decimal? TotalPrice { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? FinalPrice { get; set; }

    public string Status { get; set; }

    public short? TableId { get; set; }

    public virtual DinerProfile Diner { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Promotion Promotion { get; set; }

    public virtual RestaurantProfile Restaurant { get; set; }

    public virtual RestaurantTable Table { get; set; }
}