// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class PaymentMerchant
{
    public short Id { get; set; }

    public string BankNo { get; set; }

    public string BankAccountName { get; set; }

    public string Bank { get; set; }

    public short AccountId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual RestaurantProfile Account { get; set; }
}