// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Promotion
{
    public short PromotionId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? MinOrderValue { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? CreatedByAdmin { get; set; }

    public short? AccountId { get; set; }

    public virtual RestaurantProfile Account { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}