// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RefreshToken
{
    public long Id { get; set; }

    public short AccountId { get; set; }

    public string RefreshToken1 { get; set; }

    public bool? IsAvailable { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime ExpiredAt { get; set; }

    public string DeviceInfo { get; set; }

    public string Ipaddress { get; set; }

    public virtual Account Account { get; set; }
}