// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RestaurantLayout
{
    public short LayoutId { get; set; }

    public short AccountId { get; set; }

    public string Name { get; set; }

    public string LayoutUrl { get; set; }

    public virtual RestaurantProfile Account { get; set; }
}