// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RestaurantTable
{
    public short TableId { get; set; }

    public short AccountId { get; set; }

    public string Name { get; set; }

    public int PersonNumber { get; set; }

    public string Position { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public bool? IsVip { get; set; }

    public decimal? MinCharge { get; set; }

    public decimal? Deposit { get; set; }

    public virtual RestaurantProfile Account { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}