// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RestaurantMenu
{
    public short FoodId { get; set; }

    public short AccountId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public bool? Status { get; set; }

    public string Type { get; set; }

    public string FoodUrl { get; set; }

    public string Description { get; set; }

    public virtual RestaurantProfile Account { get; set; }

    public virtual ICollection<FoodReview> FoodReviews { get; set; } = new List<FoodReview>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}