// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Taste
{
    public short Id { get; set; }

    public short RestaurantMenuId { get; set; }

    public string Taste1 { get; set; }

    public virtual RestaurantMenu RestaurantMenu { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}