// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public int BookingId { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual Booking Booking { get; set; }
}