// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Repository.Models;

namespace Repository.DBContext;

public partial class GustoSystemContext : DbContext
{
    public GustoSystemContext()
    {
    }

    public GustoSystemContext(DbContextOptions<GustoSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<DinerProfile> DinerProfiles { get; set; }

    public virtual DbSet<Favourite> Favourites { get; set; }

    public virtual DbSet<FoodReview> FoodReviews { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<RestaurantLayout> RestaurantLayouts { get; set; }

    public virtual DbSet<RestaurantMenu> RestaurantMenus { get; set; }

    public virtual DbSet<RestaurantProfile> RestaurantProfiles { get; set; }

    public virtual DbSet<RestaurantTable> RestaurantTables { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=MSI;Initial Catalog=GustoSystem;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Account__3214EC0727AC0534");

            entity.ToTable("Account");

            entity.HasIndex(e => e.UserName, "UQ__Account__C9F28456BFF45555").IsUnique();

            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_At");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RoleId).HasColumnName("Role_Id");
            entity.Property(e => e.UpdateAt)
                .HasColumnType("datetime")
                .HasColumnName("Update_At");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Account_Role");
        });

        modelBuilder.Entity<DinerProfile>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Diner_Pr__349DA5A6CCBD2753");

            entity.ToTable("Diner_Profile");

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FacebookUrl)
                .HasMaxLength(255)
                .HasColumnName("FacebookURL");
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.Job).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.TiktokUrl)
                .HasMaxLength(255)
                .HasColumnName("TiktokURL");

            entity.HasOne(d => d.Account).WithOne(p => p.DinerProfile)
                .HasForeignKey<DinerProfile>(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DinerProfile_Account");
        });

        modelBuilder.Entity<Favourite>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Favourit__3214EC0724C13283");

            entity.ToTable("Favourite");

            entity.Property(e => e.DinerId).HasColumnName("Diner_Id");
            entity.Property(e => e.RestaurantId).HasColumnName("Restaurant_Id");

            entity.HasOne(d => d.Diner).WithMany(p => p.Favourites)
                .HasForeignKey(d => d.DinerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favourite_Diner");

            entity.HasOne(d => d.Restaurant).WithMany(p => p.Favourites)
                .HasForeignKey(d => d.RestaurantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favourite_Restaurant");
        });

        modelBuilder.Entity<FoodReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Food_Rev__F85DA78B164D90F5");

            entity.ToTable("Food_Review");

            entity.Property(e => e.ReviewId).HasColumnName("Review_Id");
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.DinerId).HasColumnName("Diner_Id");
            entity.Property(e => e.FoodId).HasColumnName("Food_Id");

            entity.HasOne(d => d.Diner).WithMany(p => p.FoodReviews)
                .HasForeignKey(d => d.DinerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Diner");

            entity.HasOne(d => d.Food).WithMany(p => p.FoodReviews)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Food");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Order__F1E4607BEFCB2A6B");

            entity.ToTable("Order");

            entity.Property(e => e.OrderId).HasColumnName("Order_Id");
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DinerId).HasColumnName("Diner_Id");
            entity.Property(e => e.RestaurantId).HasColumnName("Restaurant_Id");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Diner).WithMany(p => p.Orders)
                .HasForeignKey(d => d.DinerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Diner");

            entity.HasOne(d => d.Restaurant).WithMany(p => p.Orders)
                .HasForeignKey(d => d.RestaurantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Restaurant");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__Order_De__53D88080F8B19999");

            entity.ToTable("Order_Detail");

            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetail_Id");
            entity.Property(e => e.FoodId).HasColumnName("Food_Id");
            entity.Property(e => e.FoodPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.NumberOfFood).HasColumnName("Number_Of_Food");
            entity.Property(e => e.OrderId).HasColumnName("Order_Id");

            entity.HasOne(d => d.Food).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_Food");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_Order");
        });

        modelBuilder.Entity<RestaurantLayout>(entity =>
        {
            entity.HasKey(e => e.LayoutId).HasName("PK__Restaura__839DF101CA71D397");

            entity.ToTable("Restaurant_Layout");

            entity.Property(e => e.LayoutId).HasColumnName("Layout_Id");
            entity.Property(e => e.LayoutUrl)
                .HasMaxLength(255)
                .HasColumnName("LayoutURL");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Account).WithMany(p => p.RestaurantLayouts)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RestaurantLayout_Restaurant");
        });

        modelBuilder.Entity<RestaurantMenu>(entity =>
        {
            entity.HasKey(e => e.FoodId).HasName("PK__Restaura__B350059C484AD8EC");

            entity.ToTable("Restaurant_Menu");

            entity.Property(e => e.FoodId).HasColumnName("Food_Id");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FoodUrl)
                .HasMaxLength(255)
                .HasColumnName("FoodURL");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status).HasDefaultValue(true);
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.Account).WithMany(p => p.RestaurantMenus)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Menu_Restaurant");
        });

        modelBuilder.Entity<RestaurantProfile>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Restaura__349DA5A6550847CD");

            entity.ToTable("Restaurant_Profile");

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FacebookUrl)
                .HasMaxLength(255)
                .HasColumnName("FacebookURL");
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.OpenHour).HasMaxLength(50);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.TiktokUrl)
                .HasMaxLength(255)
                .HasColumnName("TiktokURL");

            entity.HasOne(d => d.Account).WithOne(p => p.RestaurantProfile)
                .HasForeignKey<RestaurantProfile>(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RestaurantProfile_Account");
        });

        modelBuilder.Entity<RestaurantTable>(entity =>
        {
            entity.HasKey(e => e.TableId).HasName("PK__Restaura__BAB7E67653CC6F1D");

            entity.ToTable("Restaurant_Table");

            entity.Property(e => e.TableId).HasColumnName("Table_Id");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsVip)
                .HasDefaultValue(false)
                .HasColumnName("isVIP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Position).HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.RestaurantTables)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RestaurantTable_Restaurant");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3214EC07B52D9B7F");

            entity.ToTable("Role");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}